New BG and Scripts
Added a PlayerMovement script that moves the character with "WASD" keys.

Added a 3D model in the background (serves as tracing paper for tiles in the future).

Need to add a PlayerMovement script for our secondary character with the Up/Down/Left/Right Arrow keys. (Tried to do it but got error code CS0111: Assets\RetroSoccer\Scripts\OtherPlayerScript.cs(19,18): error CS0111: Type 'NewPlayerMovement' already defines a member called 'Update' with the same parameter types).